name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  linux-x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build-linux-editor-x64
        run: |
          git submodule update --init --recursive
          pip3 install --user scons
          scons target=template_release -j $(nproc)
          scons target=template_debug -j $(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: godotmidi-linux-${{ github.sha }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/game/addons/godot_midi

  windows-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build-windows-editor-x64
        run: |
          git submodule update --init --recursive
          pip3 install --user scons
          scons target=template_release -j $env:NUMBER_OF_PROCESSORS
          scons target=template_debug -j $env:NUMBER_OF_PROCESSORS
      - uses: actions/upload-artifact@v2
        with:
          name: godotmidi-windows-${{ github.sha }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/game/addons/godot_midi

  macos-universal:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: build-macos-editor-universal
        run: |
          git submodule update --init --recursive
          brew install scons
          scons target=template_debug macos_arch=universal use_llvm=yes macos_deployment_target=10.13 -j $(sysctl -n hw.logicalcpu)
          scons target=template_release macos_arch=universal use_llvm=yes macos_deployment_target=10.13 -j $(sysctl -n hw.logicalcpu)
      - uses: actions/upload-artifact@v2
        with:
          name: godotmidi-macos-${{ github.sha }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/game/addons/godot_midi
